### ISSUE TITLE
Nested referenceFields - One Meta Link

### ISSUE THREAD

**Issue by theodorDiaconu** [Herteby/denormalize#10]
I'm almost finished with the integration, however One Meta type of links are not working.

I have the following scenario:
Author -> Profiles
Author Document: `profileId: { _id: actualProfileId }`

In this case, where nested reference fields are not an array, the cache does not work. 
This is the sample config for both:

```
I20171126-16:08:30.473(2)? cache_authors ::::: { type: 'one',
I20171126-16:08:30.473(2)?   fields: { name: 1 },
I20171126-16:08:30.473(2)?   referenceField: 'profileId:_id',
I20171126-16:08:30.473(2)?   cacheField: 'profileCache',
I20171126-16:08:30.473(2)?   bypassSchema: false }
I20171126-16:08:30.473(2)? cache_author_profiles ::::: { type: 'inverse',
I20171126-16:08:30.473(2)?   fields: { name: 1 },
I20171126-16:08:30.474(2)?   referenceField: 'profileId:_id',
I20171126-16:08:30.474(2)?   cacheField: 'authorCache',
I20171126-16:08:30.474(2)?   bypassSchema: false }
```

authorCache is empty array
profileCache is missing completely

I tried using autoMigrate, migrate to no avail.

However! The rest of the links one, one inversed, many, many inversed, many meta, many meta inversed have worked flawlessly. Amazing.

**Comment by theodorDiaconu** [comment]
Adding this:
`if(type == 'many' || type == 'many-inversed' || referenceField.indexOf(':') > -1){`
here: https://github.com/Herteby/denormalize/blob/master/cache.js#L63

Makes it work for "One Direct"

**Comment by Herteby** [comment]
Hmm, but if it's not an Array, I think you should just use a dot instead of colon, like `referenceField: 'profileId._id'`

**Comment by theodorDiaconu** [comment]
That was it, sorry for wasting your time.

**Comment by theodorDiaconu** [comment]
Managed to integrate it succesfully, all tests passing. Thank you for this great package.

**Comment by Herteby** [comment]
That is awesome! 👏
