### ISSUE TITLE
Split the cache function

### ISSUE THREAD

**Issue by theodorDiaconu** [Herteby/denormalize#2]
Your cache functions has become very big. It's very hard to maintain.

Create a lib folder and split the functionality for many, single, inversed in separate files and functions. Because this way you do the check every time for type on every after update hook.

And if they re-use thing among them modularize those functions too.

**Comment by Herteby** [comment]
Yeah I was thinking of doing this, but I just got lazy.

**Comment by theodorDiaconu** [comment]
The laziest thing a coder can do is work decoupled and good from the beginning, because he knows later he will have to do it either way.

**Comment by Herteby** [comment]
I've done the first part of the refactoring now. Instead of having 5 collection hooks with 4 if(type) in each, it is now 4 if(type) with 5 collection hooks in each. They still depend on the scope of cache() at the moment though, so it's a bit messy to split them into separate files.

**Comment by Herteby** [comment]
I think it's pretty readable now :)
