### ISSUE TITLE
Use tabs as spaces instead of \t char

### ISSUE THREAD

**Issue by theodorDiaconu** [Herteby/denormalize#3]
I recommend 4 spaces instead of 2 for indentation because it forces you to avoid spaghetti.

**Comment by Herteby** [comment]
You mean "spaces as tabs"? Or are you saying I'm using an unusual tab character? That would be news to me!

**Comment by theodorDiaconu** [comment]
4 spaces instead of one tab, because it looks weird in github. This is a coding standard

**Comment by Herteby** [comment]
Haha yeah I know about the GitHub tabs, what the hell is up with that? Why do they have tab = 8 spaces?
If you go into Edit Mode, you can change the indent size, but it doesn't save it on your profile.

**Comment by theodorDiaconu** [comment]
No clue, but let's use spaces, your IDE should have this. I recommend WebStorm

**Comment by Herteby** [comment]
I use Sublime Text :slightly_smiling_face:
A compromise then, 2 spaces.

**Comment by Herteby** [comment]
@theodorDiaconu Btw I figured out a fix for the stupid GitHub indentation :P
If you have Stylish or a similar custom CSS injector, add:
```
.blob-code{
	tab-size:4 !important;
}
```
(or maybe * instead of .blob-code, to make sure it's really applied everywhere)
