### ISSUE TITLE
Let's start using constants for our cache types.

### ISSUE THREAD

**Issue by theodorDiaconu** [Herteby/denormalize#9]
Some recommendations (something I will also do this in grapher)
export {Types} from this package and let's use
Types.ONE
Types.ONE_INVERSE
etc, instead of relying on strings.

**Comment by Herteby** [comment]
Hmm, the Google Maps API uses this pattern and I found it pretty annoying. I don't see what benefit it brings, apart from a potential miniscule performance improvement, if the constants were numbers.

**Comment by theodorDiaconu** [comment]
For me, the reason is not performance but clarity of code and autocompletion. 
You may not be sure what kind of type you have, this is why you import constants, and you never worry to check the documentation. 

Whatever you decide I would still create a CacheType constants inside grapher :D for this sole purpose

**Comment by Herteby** [comment]
Hmm, I guess it could be nice just for autocomplete. I've never gotten autocomplete to work properly though :( Tried a bunch of plugins for Sublime Text, as well as VSCode. They either got things wrong or lagged the editor.

**Comment by theodorDiaconu** [comment]
Doesn't matter. Keep the API as it is and it will be perfect! Writing a new issue now

**Comment by Herteby** [comment]
@theodorDiaconu So you dropped the constant pattern for Grapher as well?

**Comment by theodorDiaconu** [comment]
It felt too tedious... especially because we had only 2 values. 'one' and 'many'. Much easier to remember.

```js
import { Types } from 'meteor/cultofcoders:grapher';
type: Types.MANY
```

Felt less user friendly.
